### ISSUE TITLE
Add backwards compatible build plan API

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/dotnet-core-aspnet-runtime#47]
## Describe the Enhancement
The current build plan API is as follows:
```toml
[[provides]]
name = "dotnet-core-aspnet-runtime"
```
The following is a suggestion for a backwards compatible build plan API:
```toml
[[provides]]
name = "dotnet-core-aspnet-runtime"

[[or]]

[[or.provides]]
name = "dotnet-runtime"

[[or]]

[[or.provides]]
name = "dotnet-runtime"

[[or.provides]]
name = "dotnet-aspnetcore"
```

This API can be supported for some predefined period of time and then we can remove it after that point is reached hopefully giving people who use the old build plan API enough time to change their implementations. 

## Motivation
The above build plan API will allow individuals that are using buildpacks that expect the build plan API that exists from the `dotnet-core-runtime` and `dotnet-core-aspnet` buildpacks to use this buildpack instead. The only difference this will make to their image will be that the ASP.NET dependency will always be installed but this should not effect the behavior of the users application.

By setting up this API there should be no breaking change for users meaning that we can archive the `dotnet-core-runtime` and `dotnet-core-aspnet` and remove them as a support burden.
